version: "3.9"

services:
  backend:
    image: lozure.azurecr.io/backend:latest
    container_name: my-backend
    ports:
      - "3000:3000"
    env_file:
      - ./src/.env
    depends_on:
      - nlpservice  
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

  nlpservice:
    image: lozure.azurecr.io/nlpservice:latest
    container_name: nlpservice
    ports:
      - "5000:5000"

volumes:
  mongo_data: {}
